AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Skolyn contact form API (Go Lambda + API Gateway + DynamoDB)

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Timeout: 10
    MemorySize: 256

Resources:
  ContactTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  ContactApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Environment:
        Variables:
          CONTACT_TABLE_NAME: !Ref ContactTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContactTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /contact
            Method: POST
        Options:
          Type: HttpApi
          Properties:
            Path: /contact
            Method: OPTIONS
    Metadata:
      BuildMethod: makefile

Outputs:
  ContactApiBaseUrl:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Description: Base URL to use as backend target in Amplify rewrites.
